In [51]:
import numpy as np
test_array=np.array([1,4,5,8],float)
test_array

array([1., 4., 5., 8.])

In [52]:
type(test_array[3])

numpy.float64

In [69]:
matrix=[[1,2,5,8],[1,2,5,8],[1,2,5,8]]

In [70]:
np.array(matrix,int).shape

(3, 4)

In [55]:
x=np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [71]:
x=x.reshape(2,2,-1)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [74]:
my_list = [10, 20, 30, 40, 50]
print(my_list[2])  # 출력: 30

30


In [75]:
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(my_array[1, 2])  

6


In [76]:
print(my_array[2:6])

[[7 8 9]]


In [77]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(my_list[2:6])

[2, 3, 4, 5]


In [78]:
print(my_list[1:8:2])  # 출력: [1, 3, 5, 7]


[1, 3, 5, 7]


In [80]:
print(my_list[:5])  # 출력: [0, 1, 2, 3, 4]
print(my_list[5:])  # 출력: [5, 6, 7, 8, 9]
print(my_list[-4:-1])  # 출력: [6, 7, 8]



[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[6, 7, 8]


In [81]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [82]:
my_string = "Hello, World!"
print(my_string[7:12])  # 출력: 'World'


World
