In [1]:
import numpy as np
test_array = np.array([1, 4, 5, 8], float)
test_array

array([1., 4., 5., 8.])

In [ ]:
type(test_array[3])

In [ ]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

In [ ]:
print(type(test_array[3])) # 실수형(floating Type)으로 자동 형 변환 실시

In [ ]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환

In [6]:
print(test_array.shape) # 배열의 구조(shape)를 반환함

(4,)


In [7]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [8]:
tensor_rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [9]:
tensor_rank3 = [[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],[[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]] ]
np.array(tensor_rank3, int).ndim

3

In [10]:
np.array(tensor_rank3, int).size

48

In [11]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [13]:
import sys
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [14]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [15]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [16]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [17]:
x = np.array(range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [18]:
x.reshape(2,2)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [19]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [20]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
x = np.array([[1, 2, 3], [4.5, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
x[0][0]

1

In [26]:
x[0,2]

3

In [27]:
x[0, 1] = 100
x

array([[  1, 100,   3],
       [  4,   5,   6]])

In [28]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [29]:
x[1,1:3] # 1행의 1열 ~ 2열

array([7, 8])

In [30]:
x[1:3] # 1행 ~ 2행의 전체

array([[ 6,  7,  8,  9, 10]])

In [31]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [33]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [36]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [38]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [39]:
np.empty(shape=(2,4), dtype=np.float32)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

In [40]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [42]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [43]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [44]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [45]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [46]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
np.diag(matrix)

array([0, 4, 8])

In [49]:
np.diag(matrix, k=1)

array([1, 5])

In [50]:
np.random.uniform(0, 5, 10)

array([3.13301977, 3.57813659, 4.41684397, 4.45889262, 4.51792699,
       1.11296525, 2.35309548, 0.95036844, 0.26509552, 4.82677673])

In [51]:
np.random.normal(0, 2, 10)

array([ 0.84797062,  2.85388621,  2.86410113,  0.20745817,  1.24142507,
       -3.27606711, -1.78975895,  1.80834999,  4.74164831, -3.21730342])

In [2]:
import numpy as np
import inspect

# np.array 함수의 소스 코드 출력
print(inspect.getsource(np.array))


TypeError: module, class, method, function, traceback, frame, or code object was expected, got builtin_function_or_method